#%RAML 1.0 DataType
description: Response payload from ChatGPT API

properties:
  id:
    type: string
    required: true
    example: "chatcmpl-BCkySoUmdJK2t9FszIh09sltoNKFf"
  object:
    type: string
    required: true
    example: "chat.completion"
  created:
    type: integer
    required: true
    example: 1742380204
  model:
    type: string
    required: true
    example: "gpt-4o-mini-2024-07-18"
  choices:
    type: array
    required: true
    items:
      type: object
      properties:
        message:
          type: object
          properties:
            role:
              type: string
              required: true
              example: "assistant"
            content:
              type: string
              required: true
              example: "MuleSoft is a platform that helps businesses integrate their applications and data."
